version = 1
SPDX-PackageName = "NumberGuessingGame"
SPDX-PackageSupplier = "Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/Project516/NumberGuessingGame"

[[annotations]]
path = [".gitattributes", ".gitignore", ".idea/**", ".vscode/**", "gradle.properties", "renovate.json", "settings.gradle", "app/build.gradle", "gradle/libs.versions.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["README.md", "app/src/main/resources/version.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["debian-package/DEBIAN/**", "debian-package/usr/share/games/numberguessinggame/.gitignore", "debian-package/usr/games/numberguessinggame"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 the original authors"
SPDX-License-Identifier = "Apache-2.0"
