version = 1
SPDX-PackageName = "NumberGuessingGame"
SPDX-PackageSupplier = "Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/Project516/NumberGuessingGame"

[[annotations]]
path = [".idea/**", ".vscode/**", "renovate.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["app/src/main/resources/version.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["debian-package/DEBIAN/control"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Project516 <138796702+Project516@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 the original authors"
SPDX-License-Identifier = "Apache-2.0"
