# SPDX-FileCopyrightText: 2026 Project516 <138796702+Project516@users.noreply.github.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[versions]
guava = "33.5.0-jre"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
